<?php
$str_less = "
		body{
		  background-color: @body_background_color;
		  font-family: @body_font_family;
		  font-size: @body_font_size;
		  color: @text_color;
		  line-height: 1.66;
			background-image:url('@{background_path}');
			background-repeat: @background_repeat;
			background-position: @background_position;
		}

		.label{
		  color: @text_color;
		}

		a,
		a:focus,
		a:visited{
		  color: @link_color;
		}

		a:hover{
		  color: @link_hover_color;
		}

		/* GENERAL */
		.smcqp-btn,
		.spcqp-count,
		.owl-controls .owl-nav div:hover,
		.page-title:before,
		button:hover,
		.cart-container .action.continue:hover,
		a.action.primary:hover,
		.sambar-inner:before{
		  background-color: @theme_color;
		}

		.fotorama__thumb-border{
			border-color: @theme_color!important;
		}

		.fotorama__active .fotorama__dot{
			border-color: @theme_color!important;
			background-color: @theme_color;
		}

		.cart-container .cart.table-wrapper .product-item-photo .product-image-photo:hover{
			border-color: @theme_color;
		}

		.cartpro-modal .cpmodal-button{
			background-color: @theme_color;
		}

		#btn-gallery:hover{
			background-color: @theme_color;
		}

		.owl-dots .owl-dot:hover,
		.owl-dots .owl-dot.active{
			background-color: @theme_color;
		}

		.cart-container .cart-summary .coupon .actions-toolbar .primary .apply.primary:hover,
		.modal-footer .action-primary.action-accept:hover,
		.slider-ourmember .owl-dots .owl-dot:hover,
		.slider-ourmember .owl-dots .owl-dot.active{
		  background-color: @theme_color;
		}
		.navigation > ul > li:hover > a, .navigation ul > li.has-active > a{
			color: @theme_color !important;
		}
		.navigation ul > li ul li:hover, .navigation ul > li ul li.has-active,.navigation ul > li ul li.active{
			background-color: @theme_color;
			> a{color: #fff !important;}
		}
		.sm-listing-tabs .ltabs-items .ltabs-loadmore .ltabs-loadmore-btn{
			background-color: @theme_color;
			
			
		}
		.block.latest-post-container .slider-post-container .item-post .info-blog ul li{
			span:hover, a:hover{color: @theme_color !important;}
		}
		.block-minicart .minicart-items .product-item-details .product-item-name a:hover{
		  color: @theme_color !important;
		}
		.block-minicart .block-content > .actions a{
			background-color: @theme_color;
			&:hover{
				background-color: @theme_color !important;
			}
		}
		.cart-wrapper .mage-dropdown-dialog{border-color: @theme_color !important;}
		.block-minicart .minicart-items .product-item-details .product.actions .action.delete:before{
			color: @theme_color !important;
		}
		.header-style-1 .header-bottom .inner-setting-right .my-accounts .dropdown-list{
			border-color: @theme_color !important;
		}

		.fotorama__nav-wrap--horizontal .fotorama__thumb__arr--right:hover:before,
		.fotorama__nav-wrap--horizontal .fotorama__thumb__arr--left:hover:before{
		  color: @theme_color;
		}

		.fotorama-item .fotorama__nav--thumbs .fotorama__nav__frame.fotorama__active{
		  border-color: @theme_color;
		}

		.more-w .more-view:hover,.more-w .more-view:hover:before{
		 	 color: @theme_color;
		}

		.cartpro-imageload{
			border-color: @theme_color!important;
			color: @theme_color!important;
		}
		.breadcrumbs .items .item a:hover{
		  color: @theme_color;

		  
		}

		.lSAction > a {
		  &:hover{
			border-color: @theme_color;
			background-color: @theme_color;
		  }
		}
		.label-product.label-sale{
			background-color: @theme_color !important;
		}
		/* END GENERAL */

		/* LISTING */
		
		#price-slider .ui-slider-range{
			background-color: @theme_color;
		}
		#price-slider .ui-slider-handle{
			border-color: @theme_color !important;
		}
		

		.block{
		  .block-title{
			&:before{
			  background-color: @theme_color;
			}
		  }
		}

		#sm_slider_price .ui-slider-range{
			background-color: @theme_color;
		}

		#sm_slider_price .ui-slider-handle{
			border-color: @theme_color;
		}
		.item .item-inner  ul li .cat-title:hover {color: @theme_color !important;}
		.products-grid {
		  .item {
			.item-inner {
				.box-info .price-compare .link-compare:hover{
					color: @theme_color;
				}
				.box-image{
				 	.bottom-action {
				 		.btn-cart {background-color: @theme_color !important;}
				 		.btn-action:hover{background-color: #009B3E !important;}
				 	} 

				}

				
			}
		  }
		}
		.swatch-attribute.size .swatch-attribute-options .swatch-option.selected , .swatch-attribute.size .swatch-attribute-options .swatch-option:hover{
			border-color:@theme_color !important;
		}
		.products-list {
		  .item {
			.item-inner {
				 .box-image-list .btn-action:hover{
				 	 background-color: @theme_color !important;
				}
				.box-info-list {
					.swatch-attribute .swatch-attribute-options .swatch-option.selected {
						border-color:@theme_color !important;
					}
					.bottom-action .btn-action:hover,.bottom-action .btn-cart:hover{
						background-color: @theme_color !important;
					}
				}
			}
		  }
		}

		.toolbar{
		  .modes{
			.modes-mode{
			  &.mode-grid{
				&:hover,
				&.active{
				  color: @theme_color;
				}
			  }

			  &.mode-list{
				&:hover,
				&.active{
				  color: @theme_color;
				}
			  }
			}
		  }


		  .pages{
			.pages-items{
			  .item{
				&:hover{
				  background-color: @theme_color!important;
				}

				&.current{
				  background-color: @theme_color!important;

				}

			  }
			}
		  }

		}

		.products-sidebar{
		  .item{
			.item-inner{
			  .box-image{
				&:hover{
				  border-color: @theme_color;
				}
			  }
			}
		  }
		}
		.block .block-content.filter-content .filter-options-content .items li a:hover{
			color: @theme_color;
		}
		/* END LISTING */

		/* DETAIL */
		
		.vertical-style .resp-tabs-list li.active:before {
			background-color: @theme_color;
		}

		.accordion-style .resp-accordion.active{
			background-color: @theme_color!important;
			border-color: @theme_color!important;
		}


		.detail-title{
		  &:before{
			background-color: @theme_color;
		  }
		}

	
		.upsell-wrapper .owl-controls .owl-nav div:hover,
		.resp-vtabs .resp-tabs-list li:hover,
		.resp-vtabs .resp-tabs-list li.active,
		.default-style .resp-tabs-list li:hover,.default-style .resp-tabs-list li.active
		{
		  color: @theme_color;
		}



		.product-info-main{
		  .price-box .price {color: @theme_color !important;}
		  .product-options-bottom,
		  .product-add-form{
			.box-tocart{
			  .fieldset{
				.actions{
				  button{
					background-color: @theme_color !important;
				  }
				}
			  }
			}
		  }

		  .product-social-links,.product-addto-links{
			.action{
			  &:hover{
				
			  }
			}
		  }
		}

		/* horizontal full */


		.product-image-detail{
		  .thumbs-container{
			.thumb-slider{
			  .thumb-item{
				.thumb-image{
					&:hover,
					&.thumb-active{
						border-color:@theme_color;
					}
				}
			  }
			}
		  }
		}

		/* end horizontal full */

		/* END DETAIL */

		/* TAB */

		


		/* END TAB */

		/* HEADER */
		
		.cms-index-index  .header-bottom .sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li:first-child > a {
			color: @theme_color !important;
		}
		.cms-index-index  .header-style-3 .sm_megamenu_wrapper_horizontal_menu .sambar-inner .sm_megamenu_menu > li:first-child > a {
			color: @theme_color !important;
		}
		.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li {
				&.sm_megamenu_actived, &:hover{
					> a {
						color: @theme_color !important;
						&:before {
							background-color: @theme_color;
						}
					}
				}
				.sm_megamenu_actived .sm_megamenu_actived > a {color: @theme_color !important;}
				> div {
					border-color:@theme_color !important;
				}
		}
		
		.home-item-parent .mega-home-content ul li a:hover{
				color: @theme_color;
				&:before{
					background-color: @theme_color;
				}
				
		}

		.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li > div .sm_megamenu_title .sm_megamenu_title > a{
			&:hover {
				color: @theme_color;
				&:before {
					background-color: @theme_color;
				}
			}
		}
		.header-style-1{
			.header-top .dropdown-form  .switcher-trigger  strong , .header-top .dropdown-form  li a:hover{
				color: @theme_color !important;
			}
			
			.header-bottom .minicart-header .minicart-content .cart-wrapper .minicart-wrapper .showcart .counter .counter-number{
				background-color: @theme_color !important;
			}
		}

		

		
		
		#yt-totop {
		 	background-color: @theme_color;
		}
		
		/* END HEADER */

		/* HOME */
		.block .title-home::after {
			background-color: @theme_color;
		}
		
		.registered-account {
				.fieldset .actions button:hover, .more-actions a.button-reg:hover{
					background-color: @theme_color !important;
					border-color: @theme_color !important;
					color:#fff !important;
				}
		}
		.block-subscribe .form.subscribe .action-button button:hover {
				background-color: @theme_color;
		}
		/* Home 1*/
		.home-1-style {
			.slidershow-home.owl-carousel .owl-controls .owl-dots .owl-dot{
				&:hover,&.active{
					border-color: @theme_color !important;
				}
				
			}
			.block.latest-post-container .slider-post-container .item-post .info-blog .date-post {
				background-color: @theme_color !important;
			}
			.block-category .item:hover .cat h2 a {color: @theme_color;}

			.block-collection .products-grid .item .number:hover{
				background-color: @theme_color;
			}
		}
		
		
		.sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li{
			&:hover,&.tab-sel{
				color: @theme_color;
			}
		}


		

		/* END HOME */

		/* FOOTER */

		// footer 1

		.footer-container{
		  .footer-bottom{
			.copyright-footer{
			  a{
				color: @theme_color;
			  }
			}
		  }
		  .footer-block{
		  	.form.subscribe .action-button button{background-color: @theme_color !important;}
			.footer-block-content{

			  .links-footer{
				li{
				  a{
					&:hover{
					  color: @theme_color;
					}
				  }
				}
			  }

			  
			}
		  }
		}

		

		
		
		/* END FOOTER */

		/* LISTING DEALS */
		.sm-listingdeals .listingdeals-items .listingdeals-loadmore .listingdeals-loadmore-btn,
		.sm-listingdeals .listingdeals-tabs-container ul .listingdeals-tab:hover:before,
		.sm-listingdeals .listingdeals-tabs-container ul .listingdeals-tab.tab-sel:before{
			background-color: @theme_color;
		}
		/* END LISTING DEALS */

		/* LISTING EXTEND */

		.sm-listing-extend .owl-controls .owl-dots .owl-dot:hover,
		.sm-listing-extend .owl-controls .owl-dots .owl-dot.active,
		.sm-listing-extend .owl-controls .owl-nav div:hover{
			border-color: ;
		}

		/* END LISTING EXTEND */

		/* BONUS */

		.cart-container .cart.main.actions .action,
		.cart-container .cart.table-wrapper .actions-toolbar .action-edit:hover,
		.cart-container .cart.table-wrapper .actions-toolbar .action-delete:hover,
		.cart-container .checkout-methods-items .action.primary.checkout{
		  background-color: @theme_color;
		}

		/* END BONUS */

		/* PAGE */

		.pricing-title {
		  h2 {
			&:before {
			  background-color: @theme_color;
			}
		  }
		}

		.table-style-1 {
		  .table-container {
			.table-column .table-content .table-detail .button-container a {
			  &:hover{
				background-color: @theme_color;
			  }
			}
		  }
		}

		.table-style-2 {
		  .table-container {
			.table-column.column-active .table-content .table-detail .table-header {
			  color: @theme_color;
			}

			.table-column.column-active .table-content .table-detail .table-price .price{
			  color: @theme_color;
			}

			.table-column .table-content .button-container a{
				&:hover,
				&:before{
					background-color: @theme_color!important;
				}
			}

			.table-column.column-active .table-content .button-container a {
			  &:hover,
			  &:before{
				background-color: @theme_color;
			  }
			}
		  }
		}

		.table-style-4 {
		  .table-container {
			.table-column .table-content{
				.table-header,
				.button-container a {
				  background-color: @theme_color;
				}
			}
		  }
		}

		.team-style-2 {
		  .team-container {
			.team-inner .team-info {
			  background-color: @theme_color;
			}
		  }
		}

		.team-style-4 {
		  .team-container {
			.team-inner .team-info .socials li a {
			  background-color: @theme_color;
			}
		  }
		}

		.category-item .image-category .title-category h2 a:hover{
			color:@theme_color!important;
		}

		.accordion-type-1,
		.accordion-type-2,
		.accordion-type-4,
		.accordion-type-5{
			.accordion-heading .panel-title a:hover{
				color: @theme_color;
			}
		}

		.link-list {
		  li {
			a {
			  &:hover{
				color: @link_hover_color;
			  }
			}

			&.category-link-title a {
			  color: @theme_color;
			}
		  }
		}

		.testimonials-style-1 {
		  .testimonials-info {
			.name-client {
			  color: @theme_color;
			}
		  }
		}

		.events-list {
		  .item {
			.event-info {
			  .bottom-info a{
				color: @theme_color;
			  }
			}

			.event-info .event-title h2 a {
			  &:hover{
				color: @link_hover_color;
			  }
			}

		  }
		}

		.w-newsletter {
		  .newsletter-info {
			.form-newsletter-popup .action-newsletter button {
			  background-color: @theme_color !important;
			}
		  }
		}

		.socials-popup {
		  li {
			a:hover {
			  background-color: @theme_color;
			}
		  }
		}

		/* END PAGE */

		// RESPONSIVE

		@media (min-width: 1200px) {
		  .header-style-1 .header-top .header-top-links .toplinks-wrapper .header.links li.myaccount-link a {
			background-color: @theme_color;
		  }

		  .header-style-7 .header-top .header-top-links .toplinks-wrapper .header.links li.myaccount-link a {
			background-color: @theme_color;
		  }

		  .header-style-8 .header-top .header-top-links .toplinks-wrapper .header.links li.myaccount-link a {
			background-color: @theme_color;
		  }
		}

		@media (min-width: 992px) and (max-width: 1199px) {

		}

		@media (min-width: 768px) and (max-width: 991px) {
			.header-style-1 .header-middle .middle-right-content .sm-searchbox .sm-searchbox-content .actions .btn-searchbox{
				background-color: @theme_color!important;
			}

			.header-style-9 .btn-mobile,
			.header-style-11 .btn-mobile,
			.header-style-12 .btn-mobile{
				background-color: @theme_color;
			}

			.header-style-10 .header-top .toplinks-wrapper .header.links li a:hover{
				color: @theme_color;
			}

			.header-style-14 .header-middle .search-header .sm-searchbox .sm-searchbox-content .actions .btn-searchbox{
				background-color: @theme_color!important;
			}

			.header-style-14 .btn-mobile .button-mobile{
				color: @theme_color!important;
			}

			.header-style-15 .header-middle .menu-header .menu-container{
				background-color: @theme_color;
			}
		}

		@media (max-width: 768px) {
			.header-style-5 .header-middle .search-wrapper:before{
				background-color:@theme_color;
			}

			.header-style-1 .header-middle .middle-right-content .sm-searchbox .sm-searchbox-content .actions .btn-searchbox{
				background-color: @theme_color!important;
			}

			.resp-accordion.active{
				background-color:@theme_color;
				border-color:@theme_color;
			}

			.header-style-9 .btn-mobile,
			.header-style-11 .btn-mobile,
			.header-style-12 .btn-mobile{
				background-color: @theme_color;
			}

			.header-style-10 .header-top .toplinks-wrapper .header.links li a:hover{
				color: @theme_color;
			}


			.header-style-14 .header-middle .search-header .sm-searchbox .sm-searchbox-content .actions .btn-searchbox{
				background-color: @theme_color!important;
			}

			.header-style-14 .btn-mobile .button-mobile{
				color: @theme_color!important;
			}

			.header-style-15 .header-middle .menu-header .menu-container{
				background-color: @theme_color;
			}

		}

		@media (max-width: 480px) {

		}
	";
?>