<?php
	
	$_config = $this->helper('Sm\Aloza\Helper\Data');
	
	$url_static = $_config->getUrlStatic();
	$store_id = $_config->getStoreId();
	$locale = $_config->getLocale();
	$config_href = $url_static . 'frontend/Sm/aloza/'.$locale.'/css/config_' . $store_id . '.css';
	$layout_style = $_config->getThemeLayout('layout_style', $this->_coreRegistry->registry('cssgen_store'));
	$width = $_config->getThemeLayout('max_width', $this->_coreRegistry->registry('cssgen_store'));
	$background_out_boxed_color = $_config->getThemeLayout('boxed_background_color', $this->_coreRegistry->registry('cssgen_store'));
	$background_out_boxed_image = $_config->getThemeLayout('boxed_background_image', $this->_coreRegistry->registry('cssgen_store'));
	$background_out_boxed_repeat = $_config->getThemeLayout('boxed_background_repeat', $this->_coreRegistry->registry('cssgen_store'));
	$background_out_boxed_position = $_config->getThemeLayout('boxed_background_position', $this->_coreRegistry->registry('cssgen_store'));
?>

<?php
	$main_font = $_config->getGeneral('body_font');
	$main_google_font = $_config->getGeneral('body_google_font');
	$google_font_element = $_config->getGeneral('google_font_targets');
	$element_google_font_name = $_config->getGeneral('element_google_font');
	$homeStyle = $_config->getThemeLayout('home_style');
	$headerStyle = $_config->getThemeLayout('header_style');
?>
<?php if($main_font == 'google_font'){?>
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=<?php echo $main_google_font ?>" />
<?php } ?>
<?php if($google_font_element != ''){?>
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=<?php echo $element_google_font_name ?>" />
<?php } ?>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $config_href;?>" />

<!--CUSTOM CSS-->
<style>
	<?php echo $_config->getAdvanced('custom_css');?>
</style>

<script type="text/javascript">
	require([
		'domReady!',
		'jquerybootstrap',
		'yttheme'
	], function ($) {
		//console.log('Test Done');
	});
</script>


<!--CUSTOM JS-->
<?php echo $_config->getAdvanced('custom_js');?>

<script type="text/javascript">
	require([
		'jquery',
		'domReady!'
	], function ($) {
		if($('.breadcrumbs').length == 0){
			$('body').addClass("no-breadcrumbs");
		}
	});

</script>

<!--LISTING CONFIG-->
<style>

<?php echo $google_font_element ?>{
	font-family:<?php $namegooglefont_element = explode(":",str_replace("+", " ", $element_google_font_name));
		echo $namegooglefont_element[0];
	?>;
}
	
@media (min-width: 1200px) {

	<?php if($layout_style == 'wide'){?>
	.container{
		max-width: <?php echo $width . 'px';?>;
		width: <?php echo $width . 'px';?>;
	}
	<?php } ?>

	<?php if($layout_style == 'full_width'){?>
		.container{
			width: 100%;
			padding-left: 50px !important;
			padding-right: 50px !important;
		}
	<?php } ?>

	<?php if($layout_style == 'boxed'){?>
		body{
			<?php if($background_out_boxed_color){ ?>
				background-color: #<?php echo $background_out_boxed_color; ?>;
			<?php } ?>

			<?php if($background_out_boxed_image){?>
				background-image:url('<?php echo $mediaUrl . 'pattern/' . $background_out_boxed_image;?>');
				background-repeat: <?php echo $background_out_boxed_repeat;?>;
				background-position: <?php echo $background_out_boxed_position;?>;
			<?php } ?>
		}

		.page-wrapper{
			max-width: 1200px;
			margin: 0 auto;
		}
		.container{
			width: 1170px;
			padding: 0;
		}
	<?php } ?>

	/*==1 COLUMN==*/
	<?php
		$one_col_device_1200 = $_config->getProductListing('onecolumn_device_1200');
		$one_class_device_1200 = 100 / $one_col_device_1200 . '%';
	?>

	.col1-layout .category-product.products-grid .item{
		width: <?php echo $one_class_device_1200; ?>;
	}
	
	.col1-layout .category-product.products-grid .item:nth-child(<?php echo $one_col_device_1200;?>n+1){
		clear:both;
	}
	
	/*==2 COLUMNS==*/
	<?php
		$two_col_device_1200 = $_config->getProductListing('twocolumn_device_1200');
		$two_class_device_1200 = 100 / $two_col_device_1200 . '%';
	?>

	.col2-layout .category-product.products-grid .item{
		width: <?php echo $two_class_device_1200; ?>;
	}
	
	.col2-layout .category-product.products-grid .item:nth-child(<?php echo $two_col_device_1200;?>n+1){
		clear:both;
	}

	/*==3 COLUMNS==*/
	<?php
		$three_col_device_1200 = $_config->getProductListing('threecolumn_device_1200');
		$three_class_device_1200 = 100 / $three_col_device_1200 . '%';
	?>

	.col3-layout .category-product.products-grid .item{
		width: <?php echo $three_class_device_1200; ?>;
	}
	
	.col3-layout .category-product.products-grid .item:nth-child(<?php echo $three_col_device_1200;?>n+1){
		clear:both;
	}
}

@media (min-width: 992px) and (max-width: 1199px) {

	/*==1 COLUMN==*/
	<?php
		$one_col_device_992 = $_config->getProductListing('onecolumn_device_992');
		$one_class_device_992 = 100 / $one_col_device_992 . '%';
	?>

	.col1-layout .category-product.products-grid .item{
		width: <?php echo $one_class_device_992; ?>;
	}
	
	.col1-layout .category-product.products-grid .item:nth-child(<?php echo $one_col_device_992;?>n+1){
		clear:both;
	}

	/*==2 COLUMNS==*/
	<?php
		$two_col_device_992 = $_config->getProductListing('twocolumn_device_992');
		$two_class_device_992 = 100 / $two_col_device_992 . '%';
	?>

	.col2-layout .category-product.products-grid .item{
		width: <?php echo $two_class_device_992; ?>;
	}
	
	.col2-layout .category-product.products-grid .item:nth-child(<?php echo $two_col_device_992;?>n+1){
		clear:both;
	}

	/*==3 COLUMNS==*/
	<?php
		$three_col_device_992 = $_config->getProductListing('threecolumn_device_992');
		$three_class_device_992 = 100 / $three_col_device_992 . '%';
	?>

	.col3-layout .category-product.products-grid .item{
		width: <?php echo $three_class_device_992; ?>;
	}
	
	.col3-layout .category-product.products-grid .item:nth-child(<?php echo $three_col_device_992;?>n+1){
		clear:both;
	}
}

@media (min-width: 768px) and (max-width: 991px) {

	/*==1 COLUMN==*/
	<?php
		$one_col_device_768 = $_config->getProductListing('onecolumn_device_768');
		$one_class_device_768 = 100 / $one_col_device_768 . '%';
	?>

	.col1-layout .category-product.products-grid .item{
		width: <?php echo $one_class_device_768; ?>;
	}
	
	.col1-layout .category-product.products-grid .item:nth-child(<?php echo $one_col_device_768;?>n+1){
		clear:both;
	}

	/*==2 COLUMNS==*/
	<?php
		$two_col_device_768 = $_config->getProductListing('twocolumn_device_768');
		$two_class_device_768 = 100 / $two_col_device_768 . '%';
	?>

	.col2-layout .category-product.products-grid .item{
		width: <?php echo $two_class_device_768; ?>;
	}
	
	.col2-layout .category-product.products-grid .item:nth-child(<?php echo $two_col_device_768;?>n+1){
		clear:both;
	}

	/*==3 COLUMNS==*/
	<?php
	$three_col_device_768 = $_config->getProductListing('threecolumn_device_768');
	$three_class_device_768 = 100 / $three_col_device_768 . '%';
	?>

	.col3-layout .category-product.products-grid .item{
		width: <?php echo $three_class_device_768; ?>;
	}
	
	.col3-layout .category-product.products-grid .item:nth-child(<?php echo $three_col_device_768;?>n+1){
		clear:both;
	}
}

@media (min-width: 481px) and (max-width: 767px) {

	/*==1 COLUMN==*/
	<?php
		$one_col_device_481 = $_config->getProductListing('onecolumn_device_481');
		$one_class_device_481 = 100 / $one_col_device_481 . '%';
	?>

	.col1-layout .category-product.products-grid .item{
		width: <?php echo $one_class_device_481; ?>;
	}
	
	.col1-layout .category-product.products-grid .item:nth-child(<?php echo $one_col_device_481;?>n+1){
		clear:both;
	}

	/*==2 COLUMNS==*/
	<?php
	$two_col_device_481 = $_config->getProductListing('twocolumn_device_481');
	$two_class_device_481 = 100 / $two_col_device_481 . '%';
	?>

	.col2-layout .category-product.products-grid .item{
		width: <?php echo $two_class_device_481; ?>;
	}
	
	.col2-layout .category-product.products-grid .item:nth-child(<?php echo $two_col_device_481;?>n+1){
		clear:both;
	}

	/*==3 COLUMNS==*/
	<?php
		$three_col_device_481 = $_config->getProductListing('threecolumn_device_481');
		$three_class_device_481 = 100 / $three_col_device_481 . '%';
	?>

	.col3-layout .category-product.products-grid .item{
		width: <?php echo $three_class_device_481; ?>;
	}
	
	.col3-layout .category-product.products-grid .item:nth-child(<?php echo $three_col_device_481;?>n+1){
		clear:both;
	}
}

@media (max-width: 480px) {

	/*==1 COLUMN==*/
	<?php
		$one_col_device_less_481 = $_config->getProductListing('onecolumn_device_less_481');
		$one_class_device_less_481 = 100 / $one_col_device_less_481 . '%';
	?>

	.col1-layout .category-product.products-grid .item{
		width: <?php echo $one_class_device_less_481; ?>;
	}
	
	.col1-layout .category-product.products-grid .item:nth-child(<?php echo $one_col_device_less_481;?>n+1){
		clear:both;
	}

	/*==2 COLUMNS==*/
	<?php
	$two_col_device_less_481 = $_config->getProductListing('twocolumn_device_less_481');
	$two_class_device_less_481 = 100 / $two_col_device_less_481 . '%';
	?>

	.col2-layout .category-product.products-grid .item{
		width: <?php echo $two_class_device_less_481; ?>;
	}
	
	.col2-layout .category-product.products-grid .item:nth-child(<?php echo $two_col_device_less_481;?>n+1){
		clear:both;
	}

	/*==3 COLUMNS==*/
	<?php
	$three_col_device_less_481 = $_config->getProductListing('threecolumn_device_less_481');
	$three_class_device_less_481 = 100 / $three_col_device_less_481 . '%';
	?>

	.col3-layout .category-product.products-grid .item{
		width: <?php echo $three_class_device_less_481; ?>;
	}
	
	.col3-layout .category-product.products-grid .item:nth-child(<?php echo $three_col_device_less_481;?>n+1){
		clear:both;
	}
}

</style>
