<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedProducts
 */
?>

<?php
if ($exist = $block->getItems()->getSize() && $this->displayProducts()) {
    $type = 'related';
    $class = $type;

    $image = 'related_products_list';
    $title = __('Related Products');
    $items = $block->getItems();
    $limit = 0;
    $shuffle = 0;
    $canItemsAddToCart = true;

    $showWishlist = true;
    $showCompare = true;
    $showCart = false;
    $templateType = null;
    $description = false;
}

$_config = $this->helper('Sm\Aloza\Helper\Data');
$homeStyle = $_config->getThemeLayout('home_style');

?>

<?php if ($exist):?>

	<div class="related-upsell-wrapper block block-detail">
		<div class="title-home">
			<span><?php echo $title; ?></span>
		</div>
		
		<div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
			<div class="grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
				<div class="grid-product-type products list items product-items slider-products related-product-post">
					<?php $i=0; foreach ($items as $_item): $i++; 
					$objectManager = \Magento\Framework\App\ObjectManager::getInstance();		
					$product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());
					$cat       = $product->getCategoryCollection()->addAttributeToSelect('*');
					?>
					<div class="item product product-item">
						<div class="item-inner">
						<div class="product-item-info">
							<div class="box-image">
								<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
									<?php echo $block->getImage($_item, $image)->toHtml(); ?>
								</a>
								
								<!--LABEL PRODUCT-->

                                <?php
									$specialprice = $_item->getSpecialPrice();
									$specialPriceFromDate = $_item->getSpecialFromDate();
									$specialPriceToDate = $_item->getSpecialToDate();
									
									$today = time();

									if ($specialprice && $_config->getAdvanced('show_salelabel')) {
										if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) { ?>
											<div class="label-product label-sale">
												<span class="sale-product-icon">
													<?php echo __('Sale'); ?>
												</span>
											</div>
										<?php }
									}
								?>
								
								<?php
								$now = date("Y-m-d");
                                $newsFrom = substr($_item->getNewsFromDate(), 0, 10);
                                $newsTo = substr($_item->getNewsToDate(), 0, 10);
								
								if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
                                    if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) {?>
                                            <div class="label-product label-new">
												<span class="new-product-icon"><?php echo __('New'); ?></span>
											</div>
                                    <?php }
                                } ?>
								
								
								<!--END LABEL PRODUCT-->
								<div class="product actions product-item-actions bottom-action">
										<?php if($_config->getAdvanced('show_wishlist_button')){?>
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
												<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist btn-action link-wishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
													<span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
												</a>
											<?php endif; ?>
										<?php } ?>
										<?php if($_config->getAdvanced('show_addtocart_button')){?>
											<?php if ($_item->isSaleable()): ?>
												<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
													<button class="action tocart btn-cart" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
														<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>
												 <?php else: ?>
													<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
													$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
													?>
													<button class="action tocart  btn-cart" data-post='<?php /* @escapeNotVerified */ echo $postData; ?>' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
														<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>
												<?php endif; ?>
											<?php else: ?>
												<?php if ($_item->getIsSalable()): ?>
													<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										<?php } ?>
										
										
										
										
									</div>
								
							</div>
							
							<div class="product details product-item-details box-info">
								
								<h2 class="product name product-item-name product-name">
									<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
										<?php echo $block->escapeHtml($_item->getName()) ?>
									</a>
								</h2>

								<?php //echo $block->getReviewsSummaryHtml($_item, $templateType,true) ?>
								<div class="price-compare">
									<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
									<?php if($_config->getAdvanced('show_compare_button')){?>
											<?php if ($block->getAddToCompareUrl()): ?>
												<?php  $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
												<a href="#" class="action tocompare btn-action link-compare" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>' data-role="add-to-links" title="<?php /* @escapeNotVerified */ echo __('Compare'); ?>">
													<span><?php /* @escapeNotVerified */ echo __('Compare') ?></span>
												</a>
											<?php endif; ?>
										<?php } ?>

								</div>
								
							</div>
							
							
						</div>
					</div>
					</div>
					<?php if($i == $limit) break;?>
					<?php endforeach ?>
				</div>
			</div>
		</div>
	</div>

<script type="text/javascript">
	require([
		'jquery',
		'owlcarousel'
	], function ($) {
		var owl_related_product_post = $(".related-product-post");
		owl_related_product_post.owlCarousel({
			
			responsive:{
				0:{
					items:1
				},
				480:{
					items:2
				},
				768:{
					items:3
				},
				992:{
					items:4
				},
				1200:{
					items:4
				}
			},

			autoplay:false,
			loop:false,
			nav : false, // Show next and prev buttons
			dots: false,
			autoplaySpeed : 500,
			navSpeed : 500,
			dotsSpeed : 500,
			autoplayHoverPause: true,
			margin:20,

		});	  
	});	
</script>
<?php endif;?>